DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/courses/urls.py
from django.urls import path
from apps.courses.views import CourseListView,CourseDetailView,CourseLessonView,CourseCommentView,VideoView


urlpatterns = [
    path("list/", CourseListView.as_view(), name="list"),
    path("<int:course_id>/", CourseDetailView.as_view(), name="detail"),
    path("<int:course_id>/lesson", CourseLessonView.as_view(), name="lesson"),
    path("<int:course_id>/comment", CourseCommentView.as_view(), name="comment"),
    path("<int:course_id>/video/<int:video_id>/", VideoView.as_view(), name="video"),
]

apps/operations/urls.py
from django.urls import path
from apps.operations.views import AddFavoriteView,AddCommentView



urlpatterns = [
    path("fav_add/", AddFavoriteView.as_view(), name="fav_add"),
    path("add_comment/", AddCommentView.as_view(), name="add_comment"),

    # namespace是用于在下一个其内部的name前面添加namespace,在URL中,使用url:list进行定位

]

apps/organizations/urls.py
from django.urls import path
from apps.organizations.views import OrgView,AddAskView,OrgHomeView,OrgTeacherView,OrgCourseView,OrgDescView,TeacherView,TeacherDetailView



urlpatterns = [
    path("list/", OrgView.as_view(), name="list"),
    path("add_ask/", AddAskView.as_view(), name="add_ask"),
    path("<int:org_id>/", OrgHomeView.as_view(), name="home"),
    path("<int:org_id>/teacher/", OrgTeacherView.as_view(), name="teacher"),
    path("<int:org_id>/course/", OrgCourseView.as_view(), name="course"),
    path("<int:org_id>/desc/", OrgDescView.as_view(), name="desc"),
    path("teachers/", TeacherView.as_view(), name="teachers"),
    path("teachers/<int:teacher_id>/", TeacherDetailView.as_view(), name="detail"),
    # namespace是用于在下一个其内部的name前面添加namespace,在URL中,使用url:list进行定位

]

apps/users/urls.py
from django.urls import path
from .views import LoginView, LogoutView, RegisterView, DynamicLoginView,UserInfoView,UserMsgView,UserMyCourseView,UploadImageView,ChangePwdView,ChangeMobileView
from .views import MyFavOrg,MyFavCourses,MyFavTeacher
from django.views.decorators.csrf import csrf_exempt

import xadmin

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("d_login/", DynamicLoginView.as_view(), name="d_login"),  # 动态登陆Login
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("info/",UserInfoView.as_view(),name = "info"),
    path("msg/",UserMsgView.as_view(),name = "msg"),
    path("mycourses/",UserMyCourseView.as_view(),name = "mycourses"),
    path("myfavorg/",MyFavOrg.as_view(),name = "myfavorg"),
    path("myfavcourses/",MyFavCourses.as_view(),name = "myfavcourses"),
    path("myfavteacher/",MyFavTeacher.as_view(),name = "myfavteacher"),
    # 头像上传
    path("image/upload/",UploadImageView.as_view(),name = "image"),
    path("update/pwd/",ChangePwdView.as_view(),name = "update_pwd"),# 修改密码
    path("update/mobile/",ChangeMobileView.as_view(),name = "update_mobile"),# 修改手机
]

edu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls import url
from django.views.static import serve  # 用户madia目录跳转serve
import xadmin
from apps.users.views import IndexView, SendSmsView
from edu.settings import MEDIA_ROOT


urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('user/', include(('apps.users.urls','user'),namespace="user")),
    path('org/', include(('apps.organizations.urls',"organizations"),namespace="org")),
    path('ope/', include(('apps.operations.urls',"operations"),namespace="ope")),
    path('cou/', include(('apps.courses.urls',"courses"),namespace="cou")),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    #namespace是用于在下一个其内部的name前面添加namespace,在URL中,使用url:list进行定位

    # 配置验证码的URL
    path('captcha/', include('captcha.urls')),

    # 配置短信发送的url
    path('send_sms/', csrf_exempt(SendSmsView.as_view()), name="send_sms"),

    # 配置上传文件的访问url
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
]

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}首页{% endblock %} - 慕学在线网</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    {% block css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->
                </div>

                {% if request.user.is_authenticated %}
                    <div class="personal">
                        <dl class="user fr">
                            <dd>{% if user.nick_name %}{{ user.nick_name }}{% else %}{{ user.username }}{% endif %} <img
                                    class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                            <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                                <dd>
                                    <h2>django</h2>
                                    <p>{% if user.nick_name %}{{ user.nick_name }}{% else %}
                                        {{ user.username }}{% endif %}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="{% url 'user:info' %}">进入个人中心</a>
                                <a class="fr" href="{% url 'user:logout' %}">退出</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <a style="color:white" class="fr registerbtn" href="{% url 'user:register' %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'user:login' %}">登录</a>
                {% endif %}
                <a href="{% url 'user:msg' %}">
                    <div class="msg-num"><span id="MsgNum">{{ unread_nums }}</span></div>
                </a>

            </div>

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="{% static "images/logo.jpg" %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption"
                                  data-value="{% if s_type %}{{ s_type }}{% else %}course{% endif %} ">
                            {% if s_type %}
                                {% if s_type == "course" %}公开课{% endif %}
                                {% if s_type == "org" %}课程机构{% endif %}
                                {% if s_type == "teacher" %}授课教师{% endif %}
                            {% else %}
                                公开课
                            {% endif %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="{{ keywords }}"
                               placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static "images/search_btn.png" %}"
                             alt="123">
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li><a href="/">首页</a></li>
                            <li>
                                <a href="{% url 'cou:list' %}">
                                    公开课<img class="hot" src="{% static "images/nav_hot.png" %}" alt=""/>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'org:teachers' %}">授课教师</a>
                            </li>
                            <li class="active"><a href="{% url 'org:list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->


{% block custom_bread %}
{% endblock %}

{% block content %}
{% endblock %}


<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static "images/footlogo.png" %}"/></a></li>
                <li class="code"><img src="{% static "images/code.jpg" %}" alt=""/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static "images/tell.png" %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% block js %}

{% endblock %}

</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    {% block css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">

            <div class="top">
                <div class="wp">
                    <div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                    <div class="personal">
                        <dl class="user fr">
                            <dd>{% if user.nick_name %}{{ user.nick_name }}{% else %}{{ user.username }}{% endif %} <img
                                    class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                            <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                                <dd>
                                    <h2>django</h2>
                                    <p>{% if user.nick_name %}{{ user.nick_name }}{% else %}
                                        {{ user.username }}{% endif %}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="{% url 'user:info' %}">进入个人中心</a>
                                <a class="fr" href="{% url 'user:logout' %}">退出</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <a style="color:white" class="fr registerbtn" href="{% url 'user:register' %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'user:login' %}">登录</a>
                {% endif %}
                <a href="{% url 'user:msg' %}">
                    <div class="msg-num"><span id="MsgNum">{{ unread_nums }}</span></div>
                </a>

            </div>

            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px"
                         src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            {% if course_org.is_auth %}
                                <img src="{% static 'images/authentication.png' %}"/>

                            {% endif %}
                            {% if course_org.is_gold %}
                                <img src="{% static 'images/gold.png' %}"/>

                            {% endif %}

                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin" data-favid="22" data-fav-type="1">
                        {% if has_fav %}
                            已收藏
                        {% else %}
                            收藏
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'org:list' %}">课程机构</a>></li>
                <li>机构首页</li>
            </ul>
        </div>
    </section>
{% endblock %}
<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="{% ifequal current_page 'home' %}active2{% else %}{% endifequal %}"><a
                        href="{% url "org:home" course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'courses' %}active2{% else %}{% endifequal %}"><a
                        href="{% url "org:course" course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% else %}{% endifequal %}"><a
                        href="{% url "org:desc" course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% else %}{% endifequal %}"><a
                        href="{% url "org:teacher" course_org.id %}">机构讲师</a></li>
            </ul>
        </div>
        {% block content %}

        {% endblock %}
    </div>


</section>

<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

<script type="text/javascript">
    //收藏分享
    //收藏分享
    function add_fav(current_elem, fav_id, fav_type) {
        $.ajax({
            "cache": false,
            "type": "POST",
            "url": "{% url 'ope:fav_add' %}",
            "data": {'fav_id': fav_id, 'fav_type': fav_type},
            "async": true,
            "beforeSend": function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");//在没有Form表单的情况下使用csrf_token验证,ajax是个好东西
            },
            "success": function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "{% url 'user:login' %}";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == 'success') {
                    current_elem.text(data.msg)
                }
            },
        });
    }

    $(document).ready(function () {
        $('.collectionbtn').on('click', function () {
            add_fav($(this), {{ course_org.id }}, 2);
        });
    });
    $(function () {
        var $precision = $('.precision'),
            score = $precision.attr('data-star-scope'),
            option = {
                "half": true,
                "path": '{% static "images/" %}',
                "precision": true,
                "size": 24,
                "starOff": 'g_star.png',
                "starOn": 'r_star.png',
                "starHalf": 'h_star.png',
                "hints": ['极差', '差', '一般', '好评', '非常满意'],
                "noRatedMsg": '暂时还未获得评价！',
                "readOnly": true,
                "score": score
            };
        $precision.raty(option);

        $(document).ready(function () {
            $('.jsFavBtn').on('click', function () {
                var type = $(this).attr('data-fav-type');
                if (type == '1') {
                    favPraise($(this), 'fav', 1, '收藏');

                } else if (type == '3') {
                    favPraise($(this), 'fav', 3);

                } else if (type == '11') {
                    favPraise($(this), 'pra', 1);

                } else if (type == '4') {
                    favPraise($(this), 'fav', 4);

                }
            });
        });
    })
</script>


<script type="text/javascript">
    $(function () {
        $('.recordbtn1').click(function () {
            $('.recordbox1').show();
        });
        $('.recordbtn2').click(function () {
            $('.recordbox2').show();
        });

        $('.imgslide').unslider({
            "speed": 500,               //  The speed to animate each slide (in milliseconds)
            "delay": 3000,              //  The delay between slide animations (in milliseconds)
            "complete": function () {
            },  //  A function that gets called after every slide animation
            "keys": true,               //  Enable keyboard (left, right) arrow shortcuts
            "dots": true,               //  Display dot navigation
            "fluid": false              //  Support responsive design. May break non-responsive designs
        });
        var unslider = $('.imgslide').unslider();
        $('.unslider-arrow').click(function () {
            var fn = this.className.split(' ')[1];
            unslider.data('unslider')[fn]();
        });
    });
</script>
</body>
</html>